---
###############################################################################
# Configure Services
###############################################################################
# Create custom service directories and copy configuration files from ansible
# controller.

- name: 'Config | create service directories'
  ansible.builtin.file:
    path: '{{ nginx_role_root ~ "/" ~ item }}'
    owner: 'root'
    group: 'root'
    mode: '0500'
    state: 'directory'
  loop:
    - 'auth'

- name: 'Config | synchronizing files 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │         Synchronizing files. This may take a few minutes.         │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Config | set {{ _nginx_cfg_basic_auth_users.role_dest }}'
  when: _nginx_cfg_basic_auth_enable.raw
  community.general.htpasswd:
    path: '{{ _nginx_cfg_basic_auth_users.role_dest }}'
    name: '{{ item.user }}'
    password: '{{ item.pass }}'
    hash_scheme: '{{ item.hash_scheme }}'
    owner: 'root'
    group: 'root'
    mode: '0400'
    state: '{{ item.state }}'
  loop: '{{ _nginx_cfg_basic_auth_users.data }}'
  loop_control:
    label: '{{ item.user }}'

- name: 'Config | remove {{ _nginx_cfg_basic_auth_users.role_dest }}'
  when: not _nginx_cfg_basic_auth_enable.raw
  ansible.builtin.file:
    path: '{{ _nginx_cfg_basic_auth_users.role_dest }}'
    state: 'absent'

- name: 'Config | sync {{ _nginx_cfg_ca_dir.role_dest }}'
  when: _nginx_cfg_ca_dir.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_ca_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0400'
    directory_mode: '0500'

- name: 'Config | sync {{ _nginx_cfg_confd_dir.role_dest }}'
  when: _nginx_cfg_confd_dir.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_confd_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_fastcgi_params_file.role_dest }}'
  when: _nginx_cfg_fastcgi_params_file.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_fastcgi_params_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_scgi_params_file.role_dest }}'
  when: _nginx_cfg_scgi_params_file.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_scgi_params_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_uwsgi_params_file.role_dest }}'
  when: _nginx_cfg_uwsgi_params_file.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_uwsgi_params_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_mime_types_file.role_dest }}'
  when: _nginx_cfg_mime_types_file.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_mime_types_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_nginx_conf_file.role_dest }}'
  when: _nginx_cfg_nginx_conf_file.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_nginx_conf_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_web_root_dir.role_dest }}'
  when: _nginx_cfg_web_root_dir.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_web_root_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'

- name: 'Config | sync {{ _nginx_cfg_streamd_dir.role_dest }}'
  when: _nginx_cfg_streamd_dir.raw | length > 0
  ansible.builtin.include_tasks: 'sync.yml'
  vars:
    source: '{{ _nginx_cfg_streamd_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    directory_mode: '0755'
