---
###############################################################################
# Configure Services
###############################################################################

- name: '{{ "Install | filesystem | set " ~ nginx___app._default }}'
  when: nginx__srv._default | length > 0
  ansible.builtin.template:
    src: '{{ nginx__srv._default }}'
    dest: '{{ nginx___app._default }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Install | filesystem | set " ~ nginx___app._default_debug }}'
  when: nginx__srv._default_debug | length > 0
  ansible.builtin.template:
    src: '{{ nginx__srv._default_debug }}'
    dest: '{{ nginx___app._default_debug }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._conf_d }}'
  when: nginx__cfg._conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ nginx___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ nginx___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ nginx___app._conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: nginx__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ nginx__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", nginx__cfg._conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', nginx___app._conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | set " ~ nginx___app._secure_conf_d }}'
  when: nginx__cfg._secure_conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ nginx___app._secure_conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0750'
        state: 'directory'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._secure_conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ nginx___app._secure_conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0640'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._secure_conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ nginx___app._secure_conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: nginx__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ nginx__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", nginx__cfg._secure_conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', nginx___app._secure_conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | set " ~ nginx___app._fastcgi_params }}'
  when: nginx__cfg._fastcgi_params | length > 0
  ansible.builtin.template:
    src: '{{ nginx__cfg._fastcgi_params }}'
    dest: '{{ nginx___app._fastcgi_params }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._mime_types }}'
  when: nginx__cfg._mime_types | length > 0
  ansible.builtin.template:
    src: '{{ nginx__cfg._mime_types }}'
    dest: '{{ nginx___app._mime_types }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._nginx_conf }}'
  when: nginx__cfg._nginx_conf | length > 0
  ansible.builtin.template:
    src: '{{ nginx__cfg._nginx_conf }}'
    dest: '{{ nginx___app._nginx_conf }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._scgi_params }}'
  when: nginx__cfg._scgi_params | length > 0
  ansible.builtin.template:
    src: '{{ nginx__cfg._scgi_params }}'
    dest: '{{ nginx___app._scgi_params }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._uwsgi_params }}'
  when: nginx__cfg._uwsgi_params | length > 0
  ansible.builtin.template:
    src: '{{ nginx__cfg._uwsgi_params }}'
    dest: '{{ nginx___app._uwsgi_params }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ nginx___app._web_d }}'
  when: nginx__cfg._web_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ nginx___app._web_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._web_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ nginx___app._web_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        '{{ query("community.general.filetree", nginx__cfg._web_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ nginx___app._web_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: nginx__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ nginx__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", nginx__cfg._web_d) |
          map(attribute='path') |
          map('regex_replace', '^', nginx___app._web_d ~ "/") | list
        )
