---
###############################################################################
# NGINX Core
###############################################################################
# Caculate core NGINX variables for installation.
#
# Generates:
#   _nginx_root: str standardized variable (trailing slash).
#   _nginx_auth: str standardized variable (trailing slash).
#   _nginx_confd: str standardized variable (trailing slash).
#   _nginx_ca: str standardized variable (trailing slash).
#   _nginx_confd_source: str standardized variable (trailing slash).
#   _nginx_ca_source: str standardized variable (trailing slash).
#   _nginx_srv: str standardized variable (trailing slash).
#   _nginx_srv_source: str standardized variable (trailing slash).
#   _nginx_streamd: str standardized variable (trailing slash).
#   _nginx_streamd_source: str standardized variable (trailing slash).
#   _nginx_packages: list of str packages to install.
#   _nginx_load_modules: list of str paths for additional nginx modules.

- name: 'core | standardize defaults'
  ansible.builtin.set_fact:
    _nginx_default_packages:     '{{ nginx_default_os_module_packages if nginx_os_release else nginx_default_source_module_packages }}'
    _nginx_default_load_modules: '{{ nginx_load_modules if nginx_load_modules else nginx_default_os_load_modules }}'

- name: 'core | standardize source pathnames'
  ansible.builtin.set_fact:
    _nginx_root:           '{{ nginx_root if nginx_root[-1] == "/" else nginx_root+"/" }}'
    _nginx_auth:           '{{ nginx_auth if nginx_auth[-1] == "/" else nginx_auth+"/" }}'
    _nginx_confd:          '{{ nginx_confd if nginx_confd[-1] == "/" else nginx_confd+"/" }}'
    _nginx_ca:             '{{ nginx_ca if nginx_ca[-1] == "/" else nginx_ca+"/" }}'

    _nginx_confd_source:   '{{ nginx_confd_source if nginx_confd_source[-1] == "/" else nginx_confd_source+"/" }}'
    _nginx_ca_source:      '{{ nginx_ca_source if nginx_ca_source[-1] == "/" else nginx_ca_source+"/" }}'

    _nginx_srv:            '{% if nginx_srv|length > 0 %}{{ nginx_srv if nginx_srv[-1] == "/" else nginx_srv+"/" }}{% else %}""{% endif %}'
    _nginx_srv_source:     '{% if nginx_srv_source|length > 0 %}{{ nginx_srv_source if nginx_srv_source[-1] == "/" else nginx_srv_source+"/" }}{% else %}""{% endif %}'
    _nginx_streamd:        '{% if nginx_streamd|length > 0 %}{{ nginx_streamd if nginx_streamd[-1] == "/" else nginx_streamd+"/" }}{% else %}""{% endif %}'
    _nginx_streamd_source: '{% if nginx_streamd_source|length > 0 %}{{ nginx_streamd_source if nginx_streamd_source[-1] == "/" else nginx_streamd_source+"/" }}{% else %}""{% endif %}'

    _nginx_packages:       '{{ nginx_module_packages if nginx_module_packages|length > 0 else _nginx_default_packages }}'
    _nginx_load_modules:   '{{ _nginx_default_load_modules if nginx_os_release else "" }}'
