---
###############################################################################
# Install Packages
###############################################################################
# Add external NGINX APT source and required dependencies.
#
# Reference:
# * https://nginx.org/en/linux_packages.html#Debian

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ nginx_role_packages }}'
      - '{{
          _nginx_srv_packages.raw
          if _nginx_srv_packages.raw | length > 0 else
          []
        }}'
      - '{{
          nginx_role_basic_auth_packages
          if _nginx_cfg_basic_auth_enable.raw else
          []
        }}'
    apt_pins: '{{ nginx_role_apt_pins }}'
    apt_sources: '{{ nginx_role_apt_nginx }}'
    apt_package_update_cache: true
