---
###############################################################################
# NGINX Prep
###############################################################################
# Prepare system for install by creating user/group for service. Stopping
# service if enabled.

- name: 'Prep | manage users'
  when: _nginx_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ nginx_role_user }}'
    users_role_group: '{{ nginx_role_group }}'

- name: 'Prep | enumerate system user {{ _nginx_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _nginx_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _nginx_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _nginx_srv_user: '{{
        _nginx_srv_user |
        combine({"role_uid": _nginx_srv_user_query.uid})
      }}'
    _nginx_srv_group: '{{
        _nginx_srv_group |
        combine({"role_gid": _nginx_srv_user_query.group})
      }}'

- name: 'Prep | stop services'
  when: _nginx_srv_restart_enable.raw
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'nginx.service'
