---
# Service is checked for running after each role application. Apply default and
# configured options without error is success.

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | PASS ✔'
      ansible.builtin.debug:
        msg: '✔ TEST CASE PASSED'
